# Generated by Django 3.0.6 on 2020-06-29 01:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='이름')),
                ('username', models.CharField(max_length=200, unique=True, verbose_name='사용자명')),
                ('password', models.CharField(max_length=200, verbose_name='비밀번호')),
                ('email', models.CharField(max_length=200, verbose_name='이메일')),
                ('nickname', models.CharField(max_length=200, verbose_name='닉네임')),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='가입날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('blog_likes', models.ManyToManyField(blank=True, related_name='bloger_likes', to='accounts.User')),
                ('follower', models.ManyToManyField(blank=True, related_name='follower_user', to='accounts.User')),
                ('following', models.ManyToManyField(blank=True, related_name='following_user', to='accounts.User')),
            ],
            options={
                'db_table': 'USERS',
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('introduce', models.TextField(blank=True, verbose_name='자기소개')),
                ('profile_img', models.TextField(blank=True, verbose_name='프로필사진')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성날짜')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='업데이트날짜')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.User')),
                ('username', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='Profile.username+', to='accounts.User', to_field='username')),
            ],
            options={
                'db_table': 'PROFILE',
            },
        ),
    ]
